### ISSUE TITLE
sudo easy_install frida

### ISSUE THREAD

**Issue by aka001** [frida/frida-website#10]
I am unable to install frida using this command on ubuntu 14.04. Please help me.
The output of couple of commands in my system are:

->which easy_install
/usr/bin/easy_install

-> easy_install --verbose frida
http://pastebin.com/58BstLMC

-> easy_install --version
setuptools 3.3

->python -V
Python 2.7.6

**Comment by oleavr** [comment]
Ah, excellent! :+1:
