### ISSUE TITLE
frida-trace and frida-ps -U

### ISSUE THREAD

**Issue by Chunyu111** [frida/frida-website#100]
Hi 
I am new to Frida. I have followed the instructions to install frida-server on my rooted android phone.
I am running windows 10. 
After I startup the frida-server, in the cmd, I was able to run adb devices - l.  I saw my phone was connected to the laptop, However, when I tried to run frida-trace and frida-ps -U. I got the errors, frida-trace and frida-ps -U not found. 
Did I miss something? 
When frida-server was started, frida-trace and frida-ps were available? or do I need to do something to create those files?
thanks 
Chun

**Comment by oleavr** [comment]
Install the frida-tools package.
