### ISSUE TITLE
Frida crashes app upon attachment on Android

### ISSUE THREAD

**Issue by asgerfv** [frida/frida-website#101]
Hello,

I've just tried Frida for the first time, but have some issues:

1. I'm on MacOS 10.12.6 using Python 2.7.10 and a x86 Android Emulator. I installed Frida using pip, as described in https://www.frida.re/docs/installation/
2. From there the Python binding seem to work, but I have no frida-ps, frida-trace, or any frida* anywhere. I therefore downloaded the releases of those from https://build.frida.re/frida/mac/bin/
Those seem to be for Python 3 (which I then installed), but didn't work. This was due to the "sitepackage" being referenced. So I changed this. Now I could use "frida-ps -U", and correctly receive the process list.
3. So there were a bit of issues just getting started, which would be great to have fixed some how :)
4. From there I really wanted to get to work with Frida, and tried frida-trace (again after modifying the release script accordingly), but every Andoid App I try just crash right away: "Chrome keeps stopping":

$ frida-trace -U -i open com.android.chrome
Failed to attach: timed out while waiting for session to establish

adb logcat | grep chrome
=>

09-24 12:35:52.047  1597  5972 W ActivityManager: Ignoring remove of inactive process: ProcessRecord{8bacea7 0:com.android.chrome/u0a49}
09-24 12:35:53.112  1597  1608 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.chrome/com.google.android.apps.chrome.Main bnds=[849,568][1056,846]} from uid 10022
09-24 12:35:53.135  1597  1735 I ActivityManager: Start proc 6043:com.android.chrome/u0a49 for activity com.android.chrome/com.google.android.apps.chrome.Main
09-24 12:35:53.732  1597  1852 W ActivityManager: Unable to start service Intent { act=com.google.firebase.INSTANCE_ID_EVENT pkg=com.android.chrome (has extras) } U=0: not found
09-24 12:35:53.760  6043  6043 I FA      :   adb shell setprop debug.firebase.analytics.app com.android.chrome
09-24 12:35:54.003  1597  2309 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x14002000 cmp=com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity bnds=[849,568][1056,846] (has extras)} from uid 10049
09-24 12:35:54.652  6043  6064 W cr_ChildProcLauncher: Create a new ChildConnectionAllocator with package name = com.android.chrome, inSandbox = true
09-24 12:35:54.698  1597  1608 I ActivityManager: Start proc 6071:com.android.chrome:sandboxed_process0/u0i6 for webview_service com.android.chrome/org.chromium.content.app.SandboxedProcessService0
09-24 12:35:54.997  1597  1621 I ActivityManager: Displayed com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity: +915ms (total +1s864ms)
09-24 12:35:55.210  1597  1854 I ActivityManager: Start proc 6112:com.android.chrome:privileged_process0/u0a49 for service com.android.chrome/org.chromium.content.app.PrivilegedProcessService0
09-24 12:35:58.003  2359  4244 I Icing   : IndexChimeraService.getServiceInterface callingPackage=com.android.chrome componentName=null serviceId=36
09-24 12:35:58.094  6043  6167 E cr_Icing: Failed to clear legacy corpus. Status Code: 8 Message: No CorpusConfig for history of com.android.chrome
09-24 12:36:05.081  6043  6176 F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 6176 (.android.chrome)
09-24 12:36:05.089  6178  6176 F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 6178 (.android.chrome)
09-24 12:36:05.111  6184  6184 F DEBUG   : pid: 6178, tid: 6178, name: .android.chrome  >>> com.android.chrome <<<
09-24 12:36:05.164  6185  6185 F DEBUG   : pid: 6043, tid: 6176, name: .android.chrome  >>> com.android.chrome <<<
09-24 12:36:05.673  1597  6195 W ActivityManager:   Force finishing activity com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity
09-24 12:36:05.685  1597  1613 I ActivityManager: Showing crash dialog for package com.android.chrome u0
09-24 12:36:06.177  1597  1612 W ActivityManager: Activity pause timeout for ActivityRecord{59c825 u0 com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity t32 f}
09-24 12:36:17.003  1597  1612 W ActivityManager: Activity destroy timeout for ActivityRecord{59c825 u0 com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity t32 f}

And looking at the SIGSYS31:

09-24 12:37:45.458  6354  6372 D EGL_emulation: eglMakeCurrent: 0x9fa7ccc0: ver 2 0 (tinfo 0x9f4a4860)
09-24 12:37:45.807  6287  6305 I FA      : Tag Manager is not found and thus will not be used
09-24 12:37:47.164  1597  1611 E memtrack: Couldn't load memtrack module
09-24 12:37:47.164  1597  1611 W android.os.Debug: failed to get memory consumption info: -1
09-24 12:37:47.176  1597  1611 E memtrack: Couldn't load memtrack module
09-24 12:37:47.176  1597  1611 W android.os.Debug: failed to get memory consumption info: -1
09-24 12:37:47.185  1597  1611 E memtrack: Couldn't load memtrack module
09-24 12:37:47.185  1597  1611 W android.os.Debug: failed to get memory consumption info: -1
09-24 12:37:53.125  2217  3547 I ClearcutLoggerApiImpl: disconnect managed GoogleApiClient
09-24 12:37:53.614  1597  1611 E memtrack: Couldn't load memtrack module
09-24 12:37:53.614  1597  1611 W android.os.Debug: failed to get memory consumption info: -1
09-24 12:37:53.620  1597  1615 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
09-24 12:37:54.607  2162  6413 I EventLogSendingHelper: Sending log events.
09-24 12:37:56.912  6287  6416 F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 6416 (.android.chrome)
09-24 12:37:56.919  6420  6416 F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 6420 (.android.chrome)
09-24 12:37:56.930  6425  6425 W crash_dump32: failed to attach to thread 6287: Operation not permitted
09-24 12:37:56.939  6425  6425 I crash_dump32: obtaining output fd from tombstoned
09-24 12:37:56.939  1494  1494 I /system/bin/tombstoned: received crash request for pid 6287
09-24 12:37:56.940  6425  6425 I crash_dump32: performing dump of process 6287 (target tid = 6416)
09-24 12:37:56.941  6425  6425 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-24 12:37:56.941  6425  6425 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170901.008/4328566:userdebug/dev-keys'
09-24 12:37:56.941  6425  6425 F DEBUG   : Revision: '0'
09-24 12:37:56.941  6425  6425 F DEBUG   : ABI: 'x86'
09-24 12:37:56.941  6425  6425 F DEBUG   : pid: 6287, tid: 6416, name: .android.chrome  >>> com.android.chrome <<<
09-24 12:37:56.941  6425  6425 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
09-24 12:37:56.941  6425  6425 F DEBUG   : Cause: seccomp prevented call to disallowed x86 system call 7
09-24 12:37:56.942  6425  6425 F DEBUG   :     eax 00000007  ebx 00001914  ecx a41879fc  edx 40000000
09-24 12:37:56.942  6425  6425 F DEBUG   :     esi 00001914  edi a41879fc
09-24 12:37:56.942  6425  6425 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
09-24 12:37:56.942  6425  6425 F DEBUG   :     eip 9824cb4e  ebp a4278000  esp a41879dc  flags 00200282
09-24 12:37:56.943  6425  6425 F DEBUG   : 
09-24 12:37:56.943  6425  6425 F DEBUG   : backtrace:
09-24 12:37:56.943  6425  6425 F DEBUG   :     #00 pc 03848b4e  /system/app/Chrome/Chrome.apk (offset 0x1053000)
09-24 12:37:56.943  6425  6425 F DEBUG   :     #01 pc 00000003  <unknown>
09-24 12:37:56.948  6426  6426 I crash_dump32: obtaining output fd from tombstoned
09-24 12:37:56.948  1494  1494 I /system/bin/tombstoned: received crash request for pid 6420
09-24 12:37:56.948  1494  1494 I /system/bin/tombstoned: enqueueing crash request for pid 6420
09-24 12:37:57.358  1494  1494 E /system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_05
09-24 12:37:57.358  6426  6426 I crash_dump32: performing dump of process 6420 (target tid = 6420)
09-24 12:37:57.358  6426  6426 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-24 12:37:57.358  6426  6426 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.170901.008/4328566:userdebug/dev-keys'
09-24 12:37:57.358  6426  6426 F DEBUG   : Revision: '0'
09-24 12:37:57.358  6426  6426 F DEBUG   : ABI: 'x86'
09-24 12:37:57.358  6426  6426 F DEBUG   : pid: 6420, tid: 6420, name: .android.chrome  >>> com.android.chrome <<<
09-24 12:37:57.359  6426  6426 F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
09-24 12:37:57.359  6426  6426 F DEBUG   : Cause: seccomp prevented call to disallowed x86 system call 7
09-24 12:37:57.359  6426  6426 F DEBUG   :     eax 00000007  ebx 0000188f  ecx 00000000  edx 40000000
09-24 12:37:57.359  6426  6426 F DEBUG   :     esi a427bd58  edi 00000000
09-24 12:37:57.359  6426  6426 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
09-24 12:37:57.359  6426  6426 F DEBUG   :     eip 982506d2  ebp 0000188f  esp a427bbfc  flags 00200246
09-24 12:37:57.359  6426  6426 F DEBUG   : 
09-24 12:37:57.359  6426  6426 F DEBUG   : backtrace:
09-24 12:37:57.359  6426  6426 F DEBUG   :     #00 pc 0384c6d2  /system/app/Chrome/Chrome.apk (offset 0x1053000)

Since I have trouble just getting the basic stuff to work, then I suspect something obvious. But perhaps someone could help point me in the right direction?

Thanks,
Asger

**Comment by soffensive** [comment]
Although this issue is quite old, I just leave my experience here for the record. I also tried to hook functions of an Android app running in an Android emulator, and it failed for the same reason as described above.

Make sure you use the correct frida-server binary matching the architecture of your Android emulator device. In my case, I mistakenly used the binary **frida-server-10.7.7-android-x86** on my x86_64 Android emulator.

Using **frida-server-10.7.7-android-x86_64** fixed the problem and everything is working now as expected.

**Comment by oleavr** [comment]
If this is still an issue, please reopen in frida-core with details on how to reproduce it.
