### ISSUE TITLE
sudo pip install frida --ignore-installed six 报错

### ISSUE THREAD

**Issue by JoeTog** [frida/frida-website#113]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-B5XdJ1/frida/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-pUS1Pz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-B5XdJ1/frida/

**Comment by happy19375123** [comment]
/Applications/Python\ 3.6/Install\ Certificates.command
I hope this could help you

**Comment by DiamondI** [comment]
@happy19375123 
Thanks a lot! This solved my problem!
