### ISSUE TITLE
Can't find usb device.

### ISSUE THREAD

**Issue by thelittletrain171** [frida/frida-website#117]
running `frida-ps -U` leaves me with this and it never stops searching. `Waiting for USB device to appear...`  
ios 11.3.1 jailbroken iphone 8 with frida tweak added through cidia. phone is plugged into usb and i can see it in explorer but it never stops searching.

oh yeah, im on windows 10 python 3.6.6.

**Comment by oleavr** [comment]
Please reopen in frida-core with details on how to reproduce.
