### ISSUE TITLE
Failed to attach: process not found

### ISSUE THREAD

**Issue by sigs** [frida/frida-website#12]
Happened so far:
```bash
$ sudo easy_install frida
[sudo] password for me: 
Searching for frida
Reading https://pypi.python.org/simple/frida/
Best match: frida 1.6.8
Downloading https://pypi.python.org/packages/2.7/f/frida/frida-1.6.8-py2.7-linux-x86_64.egg#md5=2cdbb88696e9665929e5844365c128d4
Processing frida-1.6.8-py2.7-linux-x86_64.egg
***snip***
Finished processing dependencies for frida
$ frida-trace -i "recv*" Skype
Failed to attach: process not found                    
$
```
Now what?

**Comment by oleavr** [comment]
Is there a process called `Skype` running? You can also try it out on another application that's likely to call one of the `recv` socket functions.

**Comment by sigs** [comment]
oo, I see. I suppose my impatience exceeded the expectation of the documentation writer  (:
first starting `skype`, I get forward with that command-line magic spell. Thank you!

**Comment by sigs** [comment]
(how do i closed issue?)

**Comment by oleavr** [comment]
No worries! :) Hope you'll enjoy using Frida; and don't hesitate to submit pull-requests if you see anything you'd like to improve, be it documentation or code. Cheers!
