### ISSUE TITLE
Failed to attach - Windows 10 Pro, Frida 12.2.5, Python 3.7

### ISSUE THREAD

**Issue by lampnout** [frida/frida-website#120]
Hey folks,

I've installed Frida successfully on a Windows 10 Pro VM. However, when I attempt to attach to a process, Frida displays:
Attaching... (only after I hit the Enter key)

And after minutes of no message at all, the following is being displayed:
Failed to attach: timeout was reached

During the described issue, no further error message is being displayed.

Thanks

**Comment by ineedblood** [comment]
Unless I am missing something, why did this end up in the frida-website repo?

**Comment by oleavr** [comment]
Let's close it.

@lampnout Please reopen in frida-core if you can provide details on how to reproduce this.

**Comment by Jnchi** [comment]
He was probably reading the troubleshooting page on the website, looking for a fix for this issue.
