### ISSUE TITLE
failed to create process. Windows 10, Python 3.5 (64 bit)

### ISSUE THREAD

**Issue by nikhilgeo** [frida/frida-website#122]
OS: Windows 10
python: 3.5.0 64-bit (already tired on the 32-bit version)

Install setp followed: `pip install frida-tools`
Installation was success

```
C:\>frida-ps
failed to create process.
```

Initially python was 3.6.2 but I removed it and installed 3.5 version because I was facing below issue and read python 3.5 version will help resolve the issue. 

```
frida-ps -U

***
Failed to load the Frida native extension: DLL load failed: 
The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***
```

Any clue on how to resolve this issue ?

**Comment by oleavr** [comment]
The prebuilt Python extension for Windows requires Python 3.7. However `failed to create process` typically means that the path where Python is installed has spaces in it, and the .exe wrapper generated for each tool isn't able to handle those. Upgrading to the latest `pip` before installing `frida-tools` should solve that. And btw, this issue does not belong in frida-website.

**Comment by nikhilgeo** [comment]
https://www.frida.re/docs/installation/ says to log an issue here in case any trouble with the installation.

**Comment by oleavr** [comment]
Oops, sorry, we should fix that.
