### ISSUE TITLE
Cannot uninstall 'six'.

### ISSUE THREAD

**Issue by santoshbotre** [frida/frida-website#129]
sh-3.2# pip install frida-tools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting frida-tools
  Using cached https://files.pythonhosted.org/packages/77/51/d95d3b736e180806e57bfbec891e27b699ffee0219f822369c1b5dfc8de1/frida-tools-1.2.3.tar.gz
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in /Library/Python/2.7/site-packages (from frida-tools) (0.4.1)
Requirement already satisfied: frida<13.0.0,>=12.1.0 in /Library/Python/2.7/site-packages (from frida-tools) (12.2.30)
Collecting prompt-toolkit<3.0.0,>=2.0.0 (from frida-tools)
  Using cached https://files.pythonhosted.org/packages/f0/fe/564f7f7d2735265460225232441cb8aadee8e58e6a3cefae38220d38481e/prompt_toolkit-2.0.8-py2-none-any.whl
Collecting pygments<3.0.0,>=2.0.2 (from frida-tools)
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Requirement already satisfied: wcwidth in /Library/Python/2.7/site-packages (from prompt-toolkit<3.0.0,>=2.0.0->frida-tools) (0.1.7)
Collecting six>=1.9.0 (from prompt-toolkit<3.0.0,>=2.0.0->frida-tools)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, prompt-toolkit, pygments, frida-tools
  Found existing installation: six 1.4.1
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
sh-3.2# pip install frida-tools

**Comment by oleavr** [comment]
Disable SIP and try again.
