### ISSUE TITLE
failed to easy_install frida

### ISSUE THREAD

**Issue by mikelueng** [frida/frida-website#130]
I haved download frida egg in my computer, but failed to installed. please help me.
os: windows64
python: 3.7.2

easy_install D:\\frida-12.4.0-py2.7-win-amd64.egg
Processing frida-12.4.0-py2.7-win-amd64.egg
Removing c:\python\lib\site-packages\frida-12.4.0-py2.7-win-amd64.egg
Copying frida-12.4.0-py2.7-win-amd64.egg to c:\python\lib\site-packages
frida 12.4.0 is already the active version in easy-install.pth

Installed c:\python\lib\site-packages\frida-12.4.0-py2.7-win-amd64.egg
Processing dependencies for frida==12.4.0
Searching for frida==12.4.0
Reading https://pypi.org/simple/frida/
Download error on https://pypi.org/simple/frida/: [WinError 10061] Because the target computer refused positively, it was unable to connect. -- Some packages may not be found!
Couldn't find index page for 'frida' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [WinError 10061] Because the target computer refused positively, it was unable to connect.  -- Some packages may not be found!
No local packages or working download links found for frida==12.4.0
error: Could not find suitable distribution for Requirement.parse('frida==12.4.0')

**Comment by oleavr** [comment]
Should be fixed by now. If not try upgrading to the latest `setuptools`.
