### ISSUE TITLE
frida-ps -U

### ISSUE THREAD

**Issue by JavierViar** [frida/frida-website#132]
Whenever I use the command 'frida-ps -U', system says: 'Waiting for USB device to appear...'
![Sin título](https://user-images.githubusercontent.com/49763303/56380970-e2c56a00-6213-11e9-8c3c-e7324478de13.png)

Is this normal? If it's not, how can I fix?
I'm new in frida...thanks for your time guys.

**Comment by yujunfeng24** [comment]
for iphone: update the frida to latest version

**Comment by oleavr** [comment]
This is the expected behavior.
