### ISSUE TITLE
Error using frida in MacOS Mojave

### ISSUE THREAD

**Issue by dharmeshbaskaran** [frida/frida-website#133]
Anyone help me out how I can resolve this below issue. If I type frida in MacOS Terminal i get this issue(below).

$ frida
Traceback (most recent call last):
  File "/usr/local/bin/frida", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/frida_tools/repl.py", line 23, in main
    from prompt_toolkit.shortcuts import create_prompt_application, create_output, create_eventloop
ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/local/lib/python3.7/site-packages/prompt_toolkit/shortcuts/__init__.py)

**Comment by yujunfeng24** [comment]
> cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' 

check  python package: prompt_toolkit version

**Comment by dharmeshbaskaran** [comment]
It's prompt_toolkit 2.0.9, I've updated them till date. Still same error persist.
