### ISSUE TITLE
Issue in installing Frida

### ISSUE THREAD

**Issue by prem3010** [frida/frida-website#144]
The below error is displayed for Frida when tried to install MobSF.

 Running setup.py install for frida ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/premkumar/Downloads/Mobile-Security-Framework-MobSF-8b4016af9caa52e465812e8d6ca7cc2527c0334e/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-install-c0yg4t0o/frida/setup.py'"'"'; __file__='"'"'/private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-install-c0yg4t0o/frida/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-record-yxojpffn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/premkumar/Downloads/Mobile-Security-Framework-MobSF-8b4016af9caa52e465812e8d6ca7cc2527c0334e/venv/include/site/python3.7/frida
         cwd: /private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-install-c0yg4t0o/frida/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    copying frida/core.py -> build/lib.macosx-10.9-x86_64-3.7/frida
    running build_ext
    querying pypi for available prebuilds
    network query failed
    looking for prebuilt extension in home directory, i.e. /Users/premkumar/frida-12.7.5-py3.7-macosx-10.6-intel.egg
    no prebuilt extension found in home directory
    error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/premkumar/Downloads/Mobile-Security-Framework-MobSF-8b4016af9caa52e465812e8d6ca7cc2527c0334e/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-install-c0yg4t0o/frida/setup.py'"'"'; __file__='"'"'/private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-install-c0yg4t0o/frida/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fb/n2qp3rwn05bcmst6tld08wxh0000gn/T/pip-record-yxojpffn/install-record.txt --single-version-externally-managed --compile --install-headers /Users/premkumar/Downloads/Mobile-Security-Framework-MobSF-8b4016af9caa52e465812e8d6ca7cc2527c0334e/venv/include/site/python3.7/frida Check the logs for full command output.

**Comment by DenShaKun** [comment]
Yes, I had same issue as well, when I am trying to 'pip install frida'.

**Comment by prem3010** [comment]
@DenShaKun : If your Python version is 3.6 and above please follow the below steps. It has cleared my error

pip install certifi

Then Goto Application Folder And expand Python
In that Double click and run the Install Certificates.command

Again reinstall. Now the Frida issue will be rsolved

**Comment by avltree9798** [comment]
> @DenShaKun : If your Python version is 3.6 and above please follow the below steps. It has cleared my error
> 
> pip install certifi
> 
> Then Goto Application Folder And expand Python
> In that Double click and run the Install Certificates.command
> 
> Again reinstall. Now the Frida issue will be rsolved

Application folder as in /Applications ?
Because I don't have python folder inside Applications

**Comment by abid28june** [comment]
> > @DenShaKun : If your Python version is 3.6 and above please follow the below steps. It has cleared my error
> > pip install certifi
> > Then Goto Application Folder And expand Python
> > In that Double click and run the Install Certificates.command
> > Again reinstall. Now the Frida issue will be rsolved
> 
> Application folder as in /Applications ?
> Because I don't have python folder inside Applications

yap this resolve my issue too, install python 3.8 and open up terminal type pip install certifi or pip3 install certifi once you done this go to the application folder and you will saw a folder Python 3.8 just open it and there will be a file with the name Certificates.command just dubble click to install, that it, now reinstall the frida or tool objection, if you install the objection drida will be auto installed.

rds
ABID

**Comment by debiantano** [comment]
> @DenShaKun : si su versión de Python es 3.6 y superior, siga los pasos a continuación. ha borrado mi error
> 
> certificado de instalación de pip
> 
> Luego, vaya a la carpeta de la aplicación y expanda Python . Haga doble clic y ejecute el comando Instalar certificados.
> 
> Vuelva a instalar. Ahora el tema de Frida se resolverá.

What is the path of the folder where /Applications/Python is located?
