### ISSUE TITLE
Error Frida in Windows 10

### ISSUE THREAD

**Issue by Hamitza165** [frida/frida-website#153]
I'm installed Frida tools on my windows 10 but error where i'm check frida version 
So i can't to using this tools

This is the error 

![image](https://user-images.githubusercontent.com/35814503/70589197-b5458a80-1c01-11ea-81a5-722581908f73.png)

How to fix this ?

Thanks

**Comment by oleavr** [comment]
Use a hex editor to edit `_frida.pyd`, changing the hard-coded Python DLL name. (The Python 3.x API is stable so there's no need to recompile it.) But we will fix this soon so the patching is done automatically on Windows (this is not an issue on the other platforms).
