### ISSUE TITLE
Error in use of frida in Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by ikanekb** [frida/frida-website#16]
I've installed the frida using easy_install no problem in the installation but when I use it always same error:
***
Failed to load the Frida native extension: /home/XXXXXXX/.python-eggs/frida-3.0.1-py2.7-linux-i686.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
Please ensure that the extension was compiled for Python 2.7.
***

Do you know how to solve the problem?

Thanks

**Comment by oleavr** [comment]
Thanks for reporting. This is a known issue with the Linux build machine that produced the latest binaries, and will be fixed in the next release (coming soon). Sorry for the trouble!
