### ISSUE TITLE
run frida for android: GDBus.Error:re.frida.Error 

### ISSUE THREAD

**Issue by ling245100108** [frida/frida-website#20]
I run the following script:

import frida
import sys

session = frida.get_remote_device().attach('com.example.myapp')
print session.enumerate_modules()

The following is the output。

Traceback (most recent call last):
  File "android-test.py", line 4, in <module>
    session = frida.get_remote_device().attach('com.example.myapp')
  File "C:\Python27\lib\site-packages\frida-3.0.1-py2.7-win32.egg\frida\core.py"
, line 69, in attach
    return Session(self._impl.attach(self._pid_of(target)))
SystemError: GDBus.Error:re.frida.Error.ProcessNotResponding: GDBus.Error:re.fri
da.Error.ProcessNotResponding: Unexpectedly timed out while waiting for FIFO to
establish

What may result in this?

**Comment by oleavr** [comment]
Hi,

It looks like you're using Frida 3.0.1 with a Frida 4.x frida-server. The next release, 4.0.0, is coming soon, so in the meantime you can either:
- Build Frida yourself and continue using that bleeding edge frida-server on your device
- Switch to the old frida-server: http://build.frida.re/frida/3.x/android/arm/bin/

Cheers!

**Comment by ling245100108** [comment]
I have switch to the 3.x frida-server. But has an new error:

Traceback (most recent call last):
  File "android-test.py", line 4, in <module>
    process = frida.get_device_manager().enumerate_devices()[-1].attach("com.exa
mple.myapp")
  File "C:\Python27\lib\site-packages\frida-3.0.1-py2.7-win32.egg\frida\core.py"
, line 69, in attach
    return Session(self._impl.attach(self._pid_of(target)))
SystemError: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dqu
ark.Code24: timed out

I'm sorry to disturb you so much.

**Comment by oleavr** [comment]
Hmm. Could you please check the permissions on /data/local/tmp and the files that Frida creates there? (Check while frida-server is running, after attaching without success.) It should create a hidden directory called .frida-<random id> with some files in it. What's important here is to establish the permission of all directories leading up to /data/local/tmp/.frida-<random id>/.

No disturbance at all, I really appreciate the bug reports; really want to get this issue fixed for the upcoming release!

**Comment by ling245100108** [comment]
here is the .frida- permissions on /data/local/tmp
drwxr-xr-x root     root              2015-05-01 11:28 .frida-45700c5733281aae8398ee534f655493

cd .frida-45700c5733281aae8398ee534f655493
ls -al
-rwxr-xr-x root     root      8494620 2015-05-01 11:28 frida-agent-32.dll
-rwxr-xr-x root     root      3270980 2015-05-01 11:28 frida-helper-32

Is it right?

**Comment by oleavr** [comment]
Yep. This seems to be a duplicate of frida/frida-core#19. Let's keep discussing it there.
