### ISSUE TITLE
Windows 10 install frida-tools pip packages

### ISSUE THREAD

**Issue by cross-hello** [frida/frida-website#236]
When I hit `pip install frida-tools`, error follows:
>PS C:\Users\admin> pip install frida-tools
Looking in indexes: https://pypi.org/simple/
Collecting frida-tools
  Using cached frida-tools-10.6.1.tar.gz (47 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
\
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
\
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
\
× Encountered error while generating package metadata.
╰─> See above for output.
\
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Environment: 
    - Python 3.8.10

**Comment by azurda** [comment]
pip install setuptools

**Comment by cross-hello** [comment]
Thank you. We forget we had posted a problem. Try to ~pip install -U setuptools~ to update setuptools is ok.
Thank again for your response ☺️

May 27, 2022 17:55:41 Fernando Urbano ***@***.***>:
