### ISSUE TITLE
frida 4.0  frida.attach time out

### ISSUE THREAD

**Issue by ling245100108** [frida/frida-website#24]
The following is the error information.  And after frida.attach, the "test32" process will  segment error.
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    session = frida.attach('test32')
  File "/usr/local/lib/python2.7/dist-packages/frida-4.0.6-py2.7-linux-x86_64.egg/frida/__init__.py", line 54, in attach
    
  File "/usr/local/lib/python2.7/dist-packages/frida-4.0.6-py2.7-linux-x86_64.egg/frida/core.py", line 70, in attach
frida.ProcessNotRespondingError: timed out while waiting for session to establish

**Comment by oleavr** [comment]
Aha. Does your kernel have SELinux enabled and in enforce mode?

**Comment by ling245100108** [comment]
I use the ubuntu 14.04 kernel default.  and I set kernel.yama.ptrace_scope = 0

**Comment by oleavr** [comment]
Hmm, this could be a permission issue then. Could you check if your temp directory's latest `.frida-...` directory and its contents is accessible to the target app?

**Comment by ling245100108** [comment]
I use frida to attach the local linux process. I don't know where the .frida- directory is?

**Comment by oleavr** [comment]
Did you check in /tmp?

**Comment by ling245100108** [comment]
this is the permission in my system. 

drwxr-xr-x  2 ling ling    4096  5月 24 23:07 .frida-149734c18c726f7994158b2c6ab9fedc

-rwxr-xr-x  1 ling ling 13095632  5月 24 23:07 frida-agent-32.so
-rwxr-xr-x  1 ling ling 12987064  5月 24 23:07 frida-agent-64.so
-rwx------  1 ling ling  1567304  5月 24 23:07 frida-helper-32
-rwx------  1 ling ling  1538576  5月 24 23:07 frida-helper-64
prw-rw-rw-  1 ling ling        0  5月 24 23:07 pipe-2eb2409aad2804b893ee2035d0822bae
prw-rw-rw-  1 ling ling        0  5月 24 23:07 pipe-8ad146cba877e010f40ae5c1a934e4f7

**Comment by oleavr** [comment]
This should be fixed in newly released 4.5.1.
