### ISSUE TITLE
Error using frida in ubuntu 14.04

### ISSUE THREAD

**Issue by RoySchiffmann** [frida/frida-website#26]
Hey :)
I have successfully installed frida, I followed the steps in the installation guide for linux, and I have enabled Ptracing for non-child processes (`sudo sysctl kernel.yama.ptrace_scope=0`).
Everything went well until I tried to run the example in the installation page. To see if the problem is not specific to this example, I have tried to run the hello.c in the functions page. (http://www.frida.re/docs/functions/).
Both gave me the same response:
`user@ubuntu:~/Desktop/tmp$ sudo python hook.py 0x40057d
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/user/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)`
`Traceback (most recent call last):
  File "hook.py", line 4, in <module>
    session = frida.attach("hello")`
  `File "/usr/local/lib/python2.7/dist-packages/frida-4.0.6-py2.7-linux-x86_64.egg/frida/__init__.py", line 54, in attach`
 `File "/usr/local/lib/python2.7/dist-packages/frida-4.0.6-py2.7-linux-x86_64.egg/frida/core.py", line 70, in attach`
`frida.NotSupportedError: remote_exec PTRACE_CONT wait failed: 0`

And the process frida tried to attach to crushed with a segmentation_fault:
`user@ubuntu:~/Desktop/tmp$ ./hello`
f() is at 0x40057d
Number: 0
Number: 1
Number: 2
Number: 3
Number: 4
Number: 5
Number: 6
Number: 7
Number: 8
Number: 9
Segmentation fault (core dumped)

Any ideas why would it happen ??

**Comment by oleavr** [comment]
Hey! Sorry for the late follow-up here. Could you check with gdb what the core dump contains? You might have to build Frida yourself and disable the stripping of the binaries (by replacing the `STRIP` command with `echo` in `build/*.rc`) to get something useful.

**Comment by oleavr** [comment]
This should now be fixed in the newly released 4.5.1 release.
