### ISSUE TITLE
Frida seg fault 11

### ISSUE THREAD

**Issue by buzzcode** [frida/frida-website#32]
Hello,

I'd really like to get frida going so I can do some work with apps on my iDevice, but I'm having a heck of a time getting it to start.  I tried the easy_install route first, but ended up with problems connecting to my iPad (frida-ps would error out when I attached the iPad - sorry didn't capture the error message)

So I went the route of building frida from source.  Downloaded, ran make to do the config stuff, then ran 'make install-mac PYTHON=/Library/Frameworks/Python.framework/Versions/2.7/bin/python'  Seems like it all worked.

Fired up a python console and did the smoke-test:

jigsaw:[frida]$ python -V
Python 2.7.10
jigsaw:[frida]$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
jigsaw:[frida]$ python
Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import frida
>>> s = frida.attach("cat")
Segmentation fault: 11
jigsaw:[frida]$

**Comment by oleavr** [comment]
This should now be fixed. Let me know if the latest release (4.5.1) still proves difficult.
