### ISSUE TITLE
Failed to attach

### ISSUE THREAD

**Issue by nicotacco** [frida/frida-website#33]
I'm following the tutorial for Android; frida-ps -R works as expected but when I try to attach to Chrome I get this error message:
Failed to attach: unexpectedly timed out while waiting for FIFO to establish

Trying again the error change in 
Failed to attach: remote_exec PTRACE_CONT wait failed: 11
sometime in 
Failed to attach: remote_exec PTRACE_CONT wait failed: 5

Every time the Chrome App crash in my device.

I tried also with some other app but it's always the same problem.

Trying from a windows 7 towards a LG G2 with Lollipop device

**Comment by oleavr** [comment]
Hi,

Thanks for reporting. Which version of Frida are you seeing this on? Did you try with the latest from git?

Cheers!

**Comment by nicotacco** [comment]
Yes the one I just downloaded with easy_install on my windows and the
android server is this
http://build.frida.re/frida/android/arm/bin/frida-server

2015-09-04 3:37 GMT+02:00 Ole André Vadla Ravnås <notifications@github.com>:

**Comment by oleavr** [comment]
Ah ok, you're using the latest stable release. Lots of Android bugs have been fixed since then, and I'm aiming to release a new version soon. In the meantime, could you try the latest [snapshot](http://build.frida.re/frida-snapshot/android/arm/bin/frida-server) and let me know if it solves your issues?

**Comment by nicotacco** [comment]
Oh yes. This works very well! Thank you and keep doing this wonderful work!

2015-09-04 16:10 GMT+02:00 Ole André Vadla Ravnås <notifications@github.com>
:
