### ISSUE TITLE
can't find frida-version.h

### ISSUE THREAD

**Issue by TinyNiko** [frida/frida-website#34]
in my vs2015 ：
 Connecting to build.frida.re (build.frida.re)|176.58.104.186|:443... connected.
1>  HTTP request sent, awaiting response... 500 Internal Server Error
1>  2015-09-13 13:44:49 ERROR 500: Internal Server Error.

and then 
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006:

**Comment by oleavr** [comment]
This should no longer be an issue.
