### ISSUE TITLE
Error 404 when trying to install

### ISSUE THREAD

**Issue by buzzcode** [frida/frida-website#35]
jigsaw:[~]$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
jigsaw:[~]$ which easy_install
/Library/Frameworks/Python.framework/Versions/2.7/bin/easy_install
jigsaw:[~]$ sudo easy_install frida
Password:
Searching for frida
Reading https://pypi.python.org/simple/frida/
Best match: frida 5.0.8
Downloading https://pypi.python.org/packages/source/f/frida/frida-5.0.8.zip#md5=1887f14410fa4b8f40e7d0ca81e41264
Processing frida-5.0.8.zip
Writing /tmp/easy_install-lsQTR3/frida-5.0.8/setup.cfg
Running frida-5.0.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lsQTR3/frida-5.0.8/egg-dist-tmp-ft7fge
downloading prebuilt extension from https://pypi.python.org/packages/2.7/f/frida/frida-5.0.8-py2.7-macosx-10.10-intel.egg
error: Setup script exited with error: HTTP Error 404: Not Found

**Comment by oleavr** [comment]
Could you please try again now?

**Comment by buzzcode** [comment]
Yup, that fixed it.

thanks,
- kevin

**Comment by oleavr** [comment]
Sweet. Thanks for confirming!
