### ISSUE TITLE
Code/explanation mismatch

### ISSUE THREAD

**Issue by maktm** [frida/frida-website#41]
Over on your site, at the quickstart section (http://www.frida.re/docs/quickstart/), you posted the first snippet:

```
~ $ sudo pip install frida
~ $ frida-trace -i "recv*" -i "read*" Twitter
recv: Auto-generated handler: …/recv.js
# (snip)
recvfrom: Auto-generated handler: …/recvfrom.js
Started tracing 21 functions. Press Ctrl+C to stop.
    39 ms	recv()
   112 ms	recvfrom()
   128 ms	recvfrom()
   129 ms	recvfrom()
```

and proceeded to explain how Frida is injecting into Skype but I don't see any commands related to working with the Skype process. Am I missing something or did you update the snippet and forget to update the explanation?

**Comment by oleavr** [comment]
Oops, good catch indeed! Feel like submitting a PR by any chance? :)
