### ISSUE TITLE
Quick-start guide code errors 

### ISSUE THREAD

**Issue by daniula** [frida/frida-website#44]
* frida-trace code is not auto reloading with given commands on quickstart page
* Modified `onEnter`code in `recvfrom.js` file raise error:
```
{
    u'columnNumber': 41,
    u'lineNumber': 28,
    u'type': u'error',
    u'description': u'Error: access violation accessing 0x0',
    u'stack':
    u'Error: access violation accessing 0x0
        at [object Object].onEnter (eval at parseHandler (tracer.js:83:25), <anonymous>:28:41)
        at invokeCallback (tracer.js:31:26)
        at [object Object].Interceptor.attach.onEnter (tracer.js:37:25)'
}
```

**Comment by oleavr** [comment]
Ooh oops. This must be a case of `args[5]` being NULL, which means that the `socklen_t *` argument is NULL. Perhaps we could change the example to: `args[5].isNull() ? NULL : Memory.readPointer(args[5]).toInt32()`.

**Comment by daniula** [comment]
@oleavr Thanks. That worked. 
What about my first point? Following steps from quickstart it seems that code is not reloading. Every time I want to run new javascript code I have to kill `frida-trace` restart Twitter app on my device and then launch `frida-trace` back again. Should I submit this issue somewhere else?

**Comment by oleavr** [comment]
@daniula Sweet! Yes it would be great if you could file that in https://github.com/frida/frida-python.
