### ISSUE TITLE
Frida CLI – simple example of calc.js would be helpful

### ISSUE THREAD

**Issue by daniula** [frida/frida-website#46]
I've tried to load one of the files which was generated by running `frida-trace` but it only trigger error:
```
Failed to load script: gDBus.Error:re.frida.Error.InvalidArgument: Script(line 22): SyntaxError: Unexpected token (```

**Comment by oleavr** [comment]
We now have a new "Examples" section, so this should finally be resolved. Thanks for the feedback!
