### ISSUE TITLE
AttributeError: 'module' object has no attribute 'attach'

### ISSUE THREAD

**Issue by MarkSwanson** [frida/frida-website#6]
Using example.py on the website:
(and frida-1.0.8)

Traceback (most recent call last):
  File "./frida.py", line 1, in <module>
    import frida
  File "/home/maswanso/src/test/spidermonkey/frida.py", line 2, in <module>
    p = frida.attach("cat")
AttributeError: 'module' object has no attribute 'attach'

This happens with 1.0.5 and 1.0.8.
Ubuntu 12 - 64-bit.
Python 2.7.3

Proof I'm using 1.0.8:
strings /usr/local/bin/frida-trace
# !/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'frida==1.0.8','console_scripts','frida-trace'

**requires** = 'frida==1.0.8'
import sys
from pkg_resources import load_entry_point
if **name** == '**main**':
    sys.exit(
        load_entry_point('frida==1.0.8', 'console_scripts', 'frida-trace')()
    )

NOTE: frida-discover worked 

NOTE: frida-trace <pid> seems to work. I get:
frida-trace -i uv_accept testprog
Uploading data...
Started tracing 1 function. Press ENTER to stop.                         y/**handlers**/libuv.so.11.0.0/uv_accept.js"

(and it logs when uv_accept is called) YAY!

Modifying the **handlers** javascript also works. Yay!

However, I'm still unable to use the python API.
It doesn't help if I sudo to root.

I read that I can do much more with the Python API. 
However, I can't seem to find what new features are available using the Python API. It seems to me that the Python API has identical features to the JavaScript (__handlers*) - except that you can more easily switch between different scripts. 
Is that the difference in a nutshell?

Thanks

**Comment by mkey** [comment]
Allow me to add another D'oh!

As I was naming it frida.py I was thinking "that can't be good, don't do it, do not do it" but I did it and landed here. Dumbass.
