### ISSUE TITLE
Failed to attach: the connection is closed (iOS)

### ISSUE THREAD

**Issue by tosbaha** [frida/frida-website#61]
I am trying to use Frida on iOS but I can't attach to process. 
`frida-trace -U -i "CCCryptorCreate*" Twitter`
gives following error
`Failed to attach: the connection is closed`
I can list the processes,`frida-ps -U` is working.
Here is my setup I even tried to attach Twitter but failed. It is not related to process but Frida I guess

**OS**: macOS Sierra
**iOS** 9.3.3
**Local Frida version**: 7.3.6
**iOS Frida version**: 7.3.6

**EDIT**: It seems there was not enough space during installation of Frida. I removed couple of packages, then removed Frida and installed again. This time it worked. Is it possible for you to add some kind of script at the beginning of installation to check free space etc? Strange thing is  I didn't see any error message during first installation. You may close the issue.

**Comment by oleavr** [comment]
Fixed in latest Frida 9.x.
