### ISSUE TITLE
Unable to attach on Mac OS

### ISSUE THREAD

**Issue by IgorGanapolsky** [frida/frida-website#65]
I am following instructions on http://www.frida.re/docs/installation/.  When I try to attach Frida, I get this error:

> return Session(self._impl.attach(self._pid_of(target)))
frida.PermissionDeniedError: unable to access process with pid 67947 from the current user account

What can be done about that?

Thanks,
Igor

**Comment by oleavr** [comment]
The only way to attach to system binaries (until we provide a kernel driver in the future), is to disable SIP. We should definitely improve those docs though – they were written before SIP.

Cheers,
Ole André

**Comment by duraki** [comment]
Disabling SIP is discouraged in MacOS world. Any other way we can experiment with? @oleavr
