### ISSUE TITLE
Problem with Android example

### ISSUE THREAD

**Issue by IgorGanapolsky** [frida/frida-website#67]
I am trying to run Android example from here: http://www.frida.re/docs/examples/android/

Upon running the ctf.py script, I get this error:
> Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    process = frida.get_usb_device().attach('com.example.seccon2015.rock_paper_scissors')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/frida/core.py", line 96, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/frida/core.py", line 108, in _pid_of
    return self.get_process(target).pid
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/frida/core.py", line 66, in get_process
    matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
frida.ServerNotRunningError: unable to connect to remote frida-server: device 'ZX1PD2B527' not found

I don't understand why it is looking for device **ZX1PD2B527**, as this is not the USB device connected to my laptop (should be **01a4968dd882b783**).  Any ideas?

Thanks,
Igor

**Comment by oleavr** [comment]
Hi,

This might be a bug in how we integrate with `adb`, as that's where we get the ID from. This is the code that keeps track of the connected devices:
https://github.com/frida/frida-core/blob/e15a7c60b2685f63ab9e58606898e69693d3372a/src/droidy/droidy-client.vala#L14

Would you be interested in building Frida yourself and adding some `print ("foo\n");` lines around that code to figure out what's happening?

Cheers!
