### ISSUE TITLE
Web site lacks information about constraints / limits / versions supported

### ISSUE THREAD

**Issue by mirkobrandner** [frida/frida-website#78]
I wonder if there could not be a part of the Web site explaining certain constraints/limits/version dependencies etc.

E.g., 

- Xposed installed on an Android device will result in Java.available always return false
- frida-server not supported on Android 7.x 
- ...

As a frida-user, where would I send my information to right now? A lot of the stuff I have been looking for is also not to be found in google groups.

**Comment by oleavr** [comment]
Totally agree! Would you be interested in opening a PR adding the details that you learned so far?

**Comment by mirkobrandner** [comment]
Hi Ole,

okay, I will give it a try :-) 
Actually, I am collecting some more info and I am doing this on 8.2.2, not the latest as the latest has given me trouble. So, I probably need to redo everything for the latest versions.
PR? Are you talking about a problem report? Not sure how you want me to give that input. I guess I will file findings important to me here if I hear not back. 

Regards, Mirko

**Comment by mirkobrandner** [comment]
Frida limits and constraints

frida 8.2.2 used, needs update.

Xposed installation is clashing with Java hooking
	Java.available always false
	Thread.backtrace giving similar problems

frida-server not available for Android Intel
frida-server not (yet) running on Android 7


Not all frida API for Java implemented for ART, yet
	e.g. enumerateLoadedClassesSync()

Not clear if  Thread.backtrace can be called at all within Java.perform()

Certain frida API calls only to be made within Java.perform and not outside

Stalker?
	only available for x86?

**Comment by DARKTEMPLE9** [comment]
Is there any way to install both frida 9.0.0 and frida 8.25 on Mac ? I need to use frida 9.0.0 on ios 9.0.2 testing and frida 8.2.5 on Android 4.4 testing ? I appreciate any suggestion!

**Comment by mirkobrandner** [comment]
Operating two different frida versions on one Mac is possible I believe. 

I have accidentally installed frida 7.x per python 2 and 8.2.2 per python 3 (i.e. using pip and pip3). BUT this is probably not the way do do it correctly. I assume when you want to use the python binding you should do it per per pythons's 'virtualenv' but I have not tried this. Regarding frida, frida-ps, frida-trace etc. for different versions , you need to have these in different paths. Another tip in this context: Having different paths in different working directories you might want to apply 'direnv' hooked into your shell.

I have not tried with node.js and npm myself but that should work, too, if you do not install the node modules globally.

I hope this helps, I am not actively using two different versions at the same time myself, I am only a frida rookie as of now and not the python expert either. If the above is confusing for now, you could alternatively use VMWare Fusion Mac with a virtual Mac to have different versions of frida.

**Comment by mirkobrandner** [comment]
Regarding wether Thread.backtrace can be called at all within Java.perform(), I now use another way to get the stacktrace by using normal Java stuff because I could not get Thread.backtrace(this.context) to run. Wether this is due to ART or frida not able in general, I do not know (yet).

Look at this, not as elegant but worked for me.

----------------
"use strict";

      Java.perform(function() {
        var Activity = Java.use("com.example.<you class>.MainActivity");    
        var Exc = Java.use("java.lang.Exception");
        var LLog = Java.use("android.util.Log");
        Activity.<your method.implementation = function (v) {  // method taking a param
                        var e = Exc.$new("");
                        var log = LLog.$new();
                        console.log(log.getStackTraceString(e));
                        return "HACKED"; // in case your method returns a string
                };
    });

**Comment by mirkobrandner** [comment]
If of interest, I am no sure if Ole can or will integrate this info with some more detail in the web site's docs. My suggestion is to use https://groups.google.com/forum/#!forum/frida-dev to further discuss the handling of frida, tips and tricks, limits and constraints etc. etc. in the meantime. UNFORTUNATELY, I did not find much traffic there lately but it's on the community to change this.

**Comment by oleavr** [comment]
Nice work @mirkobrandner!

I'd be happy to merge pull-requests – we have this repo set up so new commits in the `master` branch are automatically deployed to www.frida.re, so I can promise you that PRs merged will make it live in a matter of minutes.

It should be pretty easy to get this repo cloned locally to make changes to it and review them locally before submitting, so it'd be awesome if you could give that a shot. Just holler if you hit any snags and I'll do my best to assist. Also feel free to drop by #frida on FreeNode by the way!

**Comment by DARKTEMPLE9** [comment]
Thanks @mirkobrandner . I have solved the problem on Android device.

**Comment by oleavr** [comment]
Just a small update: The latest version of Frida supports Android N, including on x86 and x86_64, is incompatible with Xposed, and the ART support is now better than the Dalvik support. (Full feature parity, and with one feature only available on Android N and above: `Java.enumerateClassLoaders()`.)

This means we don't have to update the website with these historical limitations 🎉

Cheers!
