### ISSUE TITLE
need help plz

### ISSUE THREAD

**Issue by eyahoww** [frida/frida-website#80]
this is my script
==== my script (ref. javascript api -> File) =====
import frida,sys
....
var outFile = new File("/data/local/tmp/fwdex2","wb");    <-- it's ok
write(data); <-- error (write is not defined)
flush(); <-- error (flush is not defined)
close(); <-- error (close is not defined)

i need help ;-;

**Comment by oleavr** [comment]
```js
outFile.write(data);
outFile.flush();
outFile.close();
```
