### ISSUE TITLE
iOS 9.0.3 connection refused from MacOS Sierra

### ISSUE THREAD

**Issue by z0mbi3** [frida/frida-website#94]
I'm having issues while connecting to the frida-server on my iPhone.
I'm using an old iPhone 5S running 9.0.2 (because that is what I've got jailbroken).

`frida-ps -U` works correctly from the MacBook, however, everytime I try `frida -U <appName/PID/whatever>` I get:

    MacBook:~ miguel$ frida -U 4385
        ____
        / _  |   Frida 10.2.2 - A world-class dynamic instrumentation framework
       | (_| |
        > _  |   Commands:
       /_/ |_|       help      -> Displays the help system
       . . . .       object?   -> Display information about 'object'
       . . . .       exit/quit -> Exit
       . . . .
       . . . .   More info at http://www.frida.re/docs/home/
    Failed to attach: the connection is closed

This is what is running on the iPhone:

    iPhone:~ root# frida-server --version
    10.2.2

    iPhone:~ root# frida-server
    2017-07-17 16:16:31.784 frida-server[4667:366659] Frida: Unable to check in with launchd: are we running standalone?
    2017-07-17 16:16:59.314 frida-server[4667:366665] Frida: frida-gum/gum/backend-darwin/gumdarwinmodule.c:1310:gum_darwin_module_load_image_from_blob: assertion failed: (header_64 != NULL)
    Abort trap: 6

On the MacBook I am running Sierra 10.12.5.

**Comment by oleavr** [comment]
Hi,

Two issues:
1) It appears you're running a frida-server for 32-bit devices on a 64-bit system. Did you install the correct package in Cydia?
2) frida-server should be run by launchd. This will happen automatically if you install it using our official packages.

Cheers!
