### ISSUE TITLE
how to hook "snprintf"

### ISSUE THREAD

**Issue by goodhacker** [frida/frida-website#95]
i want to hook "snprintf", this is my code:
userinfo = """
Interceptor.attach(Module.findExportByName("libcommon.so", "snprintf"),{
	onEnter:function(args){
		send("[dest=(" + Memory.readUtf8String(args[0]) + ")]");
	},
	onLeave:function(retval){
		send("[Return value: "+Memory.readUtf8String(retval) + "]");
	}
});
"""
but there is an error when i run the code:
{u'columnNumber': 1, u'description': u'Error: expected a pointer', u'fileName': u'frida/runtime/core.js', u'lineNumber': 427, u'type': u'error', u'stack': u'Error: expected a pointer\n    at frida/runtime/core.js:427\n    at script1.js:9'}

**Comment by oleavr** [comment]
The issue is that `Module.findExportByName()` returns `null` because you gave it the wrong library name or function name. (This issue does not belong in this repo, though.)
